#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend ifytexinnovations.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 430300-web-01 18.204.9.29:80
        server 430300-web-02 35.153.57.44:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
